name: Full-year calendar

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 1 1 *' # contoh, jalan setahun sekali

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Full-year Calendar Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          width: 1200
          height: 800
